### Univariate MLP Models
1. Data Preparation
2. MLP Model

In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [3]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time step
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)
print("Actual Input")
print(raw_seq)
print("Reshaped Input")
print(X)
print(X.shape)
print("Desried Output")
print(y)
print(y.shape)

Actual Input
[10, 20, 30, 40, 50, 60, 70, 80, 90]
Reshaped Input
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
(6, 3)
Desried Output
[40 50 60 70 80 90]
(6,)


In [4]:
# define model
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=n_steps))
model.add(Dense(units=1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(x=X, y=y, epochs=2000, verbose=True)

Train on 6 samples
Epoch 1/2000
6/6 [==============================] - 0s 81ms/sample - loss: 3350.0540
Epoch 2/2000
6/6 [==============================] - 0s 246us/sample - loss: 3198.1086
Epoch 3/2000
6/6 [==============================] - 0s 276us/sample - loss: 3050.6560
Epoch 4/2000
6/6 [==============================] - 0s 289us/sample - loss: 2906.9138
Epoch 5/2000
6/6 [==============================] - 0s 265us/sample - loss: 2767.3938
Epoch 6/2000
6/6 [==============================] - 0s 292us/sample - loss: 2631.8445
Epoch 7/2000
6/6 [==============================] - 0s 291us/sample - loss: 2500.0471
Epoch 8/2000
6/6 [==============================] - 0s 257us/sample - loss: 2371.9685
Epoch 9/2000
6/6 [==============================] - 0s 271us/sample - loss: 2247.6135
Epoch 10/2000
6/6 [==============================] - 0s 279us/sample - loss: 2127.1482
Epoch 11/2000
6/6 [==============================] - 0s 261us/sample - loss: 2010.5848
Epoch 12/2000
6/6 [===============

Epoch 97/2000
6/6 [==============================] - 0s 261us/sample - loss: 41.4892
Epoch 98/2000
6/6 [==============================] - 0s 285us/sample - loss: 41.3880
Epoch 99/2000
6/6 [==============================] - 0s 271us/sample - loss: 41.2957
Epoch 100/2000
6/6 [==============================] - 0s 254us/sample - loss: 41.2116
Epoch 101/2000
6/6 [==============================] - 0s 245us/sample - loss: 41.1343
Epoch 102/2000
6/6 [==============================] - 0s 250us/sample - loss: 41.0629
Epoch 103/2000
6/6 [==============================] - 0s 261us/sample - loss: 40.9964
Epoch 104/2000
6/6 [==============================] - 0s 292us/sample - loss: 40.9338
Epoch 105/2000
6/6 [==============================] - 0s 285us/sample - loss: 40.8742
Epoch 106/2000
6/6 [==============================] - 0s 285us/sample - loss: 40.8168
Epoch 107/2000
6/6 [==============================] - 0s 285us/sample - loss: 40.7610
Epoch 108/2000
6/6 [==============================] - 0s 

Epoch 193/2000
6/6 [==============================] - 0s 255us/sample - loss: 35.1181
Epoch 194/2000
6/6 [==============================] - 0s 274us/sample - loss: 35.0481
Epoch 195/2000
6/6 [==============================] - 0s 236us/sample - loss: 34.9779
Epoch 196/2000
6/6 [==============================] - 0s 256us/sample - loss: 34.9076
Epoch 197/2000
6/6 [==============================] - 0s 260us/sample - loss: 34.8372
Epoch 198/2000
6/6 [==============================] - 0s 236us/sample - loss: 34.7667
Epoch 199/2000
6/6 [==============================] - 0s 222us/sample - loss: 34.6961
Epoch 200/2000
6/6 [==============================] - 0s 247us/sample - loss: 34.6254
Epoch 201/2000
6/6 [==============================] - 0s 282us/sample - loss: 34.5546
Epoch 202/2000
6/6 [==============================] - 0s 246us/sample - loss: 34.4837
Epoch 203/2000
6/6 [==============================] - 0s 235us/sample - loss: 34.4126
Epoch 204/2000
6/6 [==============================] - 

Epoch 289/2000
6/6 [==============================] - 0s 218us/sample - loss: 28.3131
Epoch 290/2000
6/6 [==============================] - 0s 250us/sample - loss: 28.2401
Epoch 291/2000
6/6 [==============================] - 0s 224us/sample - loss: 28.1670
Epoch 292/2000
6/6 [==============================] - 0s 275us/sample - loss: 28.0939
Epoch 293/2000
6/6 [==============================] - 0s 236us/sample - loss: 28.0208
Epoch 294/2000
6/6 [==============================] - 0s 238us/sample - loss: 27.9475
Epoch 295/2000
6/6 [==============================] - 0s 263us/sample - loss: 27.8741
Epoch 296/2000
6/6 [==============================] - 0s 249us/sample - loss: 27.8007
Epoch 297/2000
6/6 [==============================] - 0s 240us/sample - loss: 27.7272
Epoch 298/2000
6/6 [==============================] - 0s 245us/sample - loss: 27.6551
Epoch 299/2000
6/6 [==============================] - 0s 237us/sample - loss: 27.5831
Epoch 300/2000
6/6 [==============================] - 

Epoch 385/2000
6/6 [==============================] - 0s 286us/sample - loss: 21.1881
Epoch 386/2000
6/6 [==============================] - 0s 298us/sample - loss: 21.1126
Epoch 387/2000
6/6 [==============================] - 0s 293us/sample - loss: 21.0369
Epoch 388/2000
6/6 [==============================] - 0s 309us/sample - loss: 20.9614
Epoch 389/2000
6/6 [==============================] - 0s 299us/sample - loss: 20.8858
Epoch 390/2000
6/6 [==============================] - 0s 276us/sample - loss: 20.8102
Epoch 391/2000
6/6 [==============================] - 0s 276us/sample - loss: 20.7347
Epoch 392/2000
6/6 [==============================] - 0s 334us/sample - loss: 20.6591
Epoch 393/2000
6/6 [==============================] - 0s 276us/sample - loss: 20.5835
Epoch 394/2000
6/6 [==============================] - 0s 292us/sample - loss: 20.5079
Epoch 395/2000
6/6 [==============================] - 0s 345us/sample - loss: 20.4324
Epoch 396/2000
6/6 [==============================] - 

Epoch 481/2000
6/6 [==============================] - 0s 308us/sample - loss: 14.0735
Epoch 482/2000
6/6 [==============================] - 0s 320us/sample - loss: 14.0028
Epoch 483/2000
6/6 [==============================] - 0s 445us/sample - loss: 13.9322
Epoch 484/2000
6/6 [==============================] - 0s 373us/sample - loss: 13.8618
Epoch 485/2000
6/6 [==============================] - 0s 353us/sample - loss: 13.7914
Epoch 486/2000
6/6 [==============================] - 0s 335us/sample - loss: 13.7212
Epoch 487/2000
6/6 [==============================] - 0s 363us/sample - loss: 13.6511
Epoch 488/2000
6/6 [==============================] - 0s 481us/sample - loss: 13.5810
Epoch 489/2000
6/6 [==============================] - 0s 379us/sample - loss: 13.5112
Epoch 490/2000
6/6 [==============================] - 0s 550us/sample - loss: 13.4414
Epoch 491/2000
6/6 [==============================] - 0s 371us/sample - loss: 13.3718
Epoch 492/2000
6/6 [==============================] - 

Epoch 577/2000
6/6 [==============================] - 0s 339us/sample - loss: 7.9719
Epoch 578/2000
6/6 [==============================] - 0s 293us/sample - loss: 7.9174
Epoch 579/2000
6/6 [==============================] - 0s 257us/sample - loss: 7.8628
Epoch 580/2000
6/6 [==============================] - 0s 269us/sample - loss: 7.8079
Epoch 581/2000
6/6 [==============================] - 0s 292us/sample - loss: 7.7531
Epoch 582/2000
6/6 [==============================] - 0s 260us/sample - loss: 7.6984
Epoch 583/2000
6/6 [==============================] - 0s 248us/sample - loss: 7.6440
Epoch 584/2000
6/6 [==============================] - 0s 280us/sample - loss: 7.5900
Epoch 585/2000
6/6 [==============================] - 0s 341us/sample - loss: 7.5363
Epoch 586/2000
6/6 [==============================] - 0s 260us/sample - loss: 7.4831
Epoch 587/2000
6/6 [==============================] - 0s 264us/sample - loss: 7.4301
Epoch 588/2000
6/6 [==============================] - 0s 259us/sa

Epoch 674/2000
6/6 [==============================] - 0s 249us/sample - loss: 3.6911
Epoch 675/2000
6/6 [==============================] - 0s 251us/sample - loss: 3.6583
Epoch 676/2000
6/6 [==============================] - 0s 253us/sample - loss: 3.6254
Epoch 677/2000
6/6 [==============================] - 0s 247us/sample - loss: 3.5926
Epoch 678/2000
6/6 [==============================] - 0s 244us/sample - loss: 3.5599
Epoch 679/2000
6/6 [==============================] - 0s 235us/sample - loss: 3.5276
Epoch 680/2000
6/6 [==============================] - 0s 244us/sample - loss: 3.4956
Epoch 681/2000
6/6 [==============================] - 0s 236us/sample - loss: 3.4639
Epoch 682/2000
6/6 [==============================] - 0s 243us/sample - loss: 3.4326
Epoch 683/2000
6/6 [==============================] - 0s 289us/sample - loss: 3.4015
Epoch 684/2000
6/6 [==============================] - 0s 261us/sample - loss: 3.3707
Epoch 685/2000
6/6 [==============================] - 0s 236us/sa

Epoch 771/2000
6/6 [==============================] - 0s 238us/sample - loss: 1.3992
Epoch 772/2000
6/6 [==============================] - 0s 342us/sample - loss: 1.3837
Epoch 773/2000
6/6 [==============================] - 0s 459us/sample - loss: 1.3684
Epoch 774/2000
6/6 [==============================] - 0s 454us/sample - loss: 1.3535
Epoch 775/2000
6/6 [==============================] - 0s 489us/sample - loss: 1.3387
Epoch 776/2000
6/6 [==============================] - 0s 363us/sample - loss: 1.3240
Epoch 777/2000
6/6 [==============================] - 0s 361us/sample - loss: 1.3093
Epoch 778/2000
6/6 [==============================] - 0s 309us/sample - loss: 1.2955
Epoch 779/2000
6/6 [==============================] - 0s 316us/sample - loss: 1.2799
Epoch 780/2000
6/6 [==============================] - 0s 320us/sample - loss: 1.2658
Epoch 781/2000
6/6 [==============================] - 0s 317us/sample - loss: 1.2520
Epoch 782/2000
6/6 [==============================] - 0s 316us/sa

Epoch 868/2000
6/6 [==============================] - 0s 368us/sample - loss: 0.4334
Epoch 869/2000
6/6 [==============================] - 0s 540us/sample - loss: 0.4266
Epoch 870/2000
6/6 [==============================] - 0s 502us/sample - loss: 0.4210
Epoch 871/2000
6/6 [==============================] - 0s 510us/sample - loss: 0.4155
Epoch 872/2000
6/6 [==============================] - 0s 522us/sample - loss: 0.4102
Epoch 873/2000
6/6 [==============================] - 0s 449us/sample - loss: 0.4048
Epoch 874/2000
6/6 [==============================] - 0s 470us/sample - loss: 0.3996
Epoch 875/2000
6/6 [==============================] - 0s 267us/sample - loss: 0.3943
Epoch 876/2000
6/6 [==============================] - 0s 414us/sample - loss: 0.3891
Epoch 877/2000
6/6 [==============================] - 0s 309us/sample - loss: 0.3838
Epoch 878/2000
6/6 [==============================] - 0s 402us/sample - loss: 0.3786
Epoch 879/2000
6/6 [==============================] - 0s 338us/sa

Epoch 965/2000
6/6 [==============================] - 0s 298us/sample - loss: 0.1089
Epoch 966/2000
6/6 [==============================] - 0s 307us/sample - loss: 0.1073
Epoch 967/2000
6/6 [==============================] - 0s 281us/sample - loss: 0.1058
Epoch 968/2000
6/6 [==============================] - 0s 305us/sample - loss: 0.1042
Epoch 969/2000
6/6 [==============================] - 0s 294us/sample - loss: 0.1027
Epoch 970/2000
6/6 [==============================] - 0s 256us/sample - loss: 0.1011
Epoch 971/2000
6/6 [==============================] - 0s 258us/sample - loss: 0.0995
Epoch 972/2000
6/6 [==============================] - 0s 254us/sample - loss: 0.0979
Epoch 973/2000
6/6 [==============================] - 0s 233us/sample - loss: 0.0964
Epoch 974/2000
6/6 [==============================] - 0s 242us/sample - loss: 0.0949
Epoch 975/2000
6/6 [==============================] - 0s 253us/sample - loss: 0.0937
Epoch 976/2000
6/6 [==============================] - 0s 253us/sa

Epoch 1061/2000
6/6 [==============================] - 0s 265us/sample - loss: 0.0231
Epoch 1062/2000
6/6 [==============================] - 0s 259us/sample - loss: 0.0228
Epoch 1063/2000
6/6 [==============================] - 0s 272us/sample - loss: 0.0224
Epoch 1064/2000
6/6 [==============================] - 0s 289us/sample - loss: 0.0220
Epoch 1065/2000
6/6 [==============================] - 0s 286us/sample - loss: 0.0216
Epoch 1066/2000
6/6 [==============================] - 0s 251us/sample - loss: 0.0212
Epoch 1067/2000
6/6 [==============================] - 0s 258us/sample - loss: 0.0209
Epoch 1068/2000
6/6 [==============================] - 0s 262us/sample - loss: 0.0205
Epoch 1069/2000
6/6 [==============================] - 0s 237us/sample - loss: 0.0202
Epoch 1070/2000
6/6 [==============================] - 0s 236us/sample - loss: 0.0198
Epoch 1071/2000
6/6 [==============================] - 0s 265us/sample - loss: 0.0195
Epoch 1072/2000
6/6 [==============================] -

Epoch 1157/2000
6/6 [==============================] - 0s 508us/sample - loss: 0.0042
Epoch 1158/2000
6/6 [==============================] - 0s 370us/sample - loss: 0.0041
Epoch 1159/2000
6/6 [==============================] - 0s 394us/sample - loss: 0.0040
Epoch 1160/2000
6/6 [==============================] - 0s 521us/sample - loss: 0.0039
Epoch 1161/2000
6/6 [==============================] - 0s 425us/sample - loss: 0.0039
Epoch 1162/2000
6/6 [==============================] - 0s 373us/sample - loss: 0.0038
Epoch 1163/2000
6/6 [==============================] - 0s 394us/sample - loss: 0.0037
Epoch 1164/2000
6/6 [==============================] - 0s 519us/sample - loss: 0.0036
Epoch 1165/2000
6/6 [==============================] - 0s 460us/sample - loss: 0.0036
Epoch 1166/2000
6/6 [==============================] - 0s 403us/sample - loss: 0.0035
Epoch 1167/2000
6/6 [==============================] - 0s 687us/sample - loss: 0.0034
Epoch 1168/2000
6/6 [==============================] -

Epoch 1252/2000
6/6 [==============================] - 0s 303us/sample - loss: 6.5386e-04
Epoch 1253/2000
6/6 [==============================] - 0s 289us/sample - loss: 6.3779e-04
Epoch 1254/2000
6/6 [==============================] - 0s 278us/sample - loss: 6.2532e-04
Epoch 1255/2000
6/6 [==============================] - 0s 307us/sample - loss: 6.1262e-04
Epoch 1256/2000
6/6 [==============================] - 0s 315us/sample - loss: 6.0059e-04
Epoch 1257/2000
6/6 [==============================] - 0s 259us/sample - loss: 5.8871e-04
Epoch 1258/2000
6/6 [==============================] - 0s 261us/sample - loss: 5.7710e-04
Epoch 1259/2000
6/6 [==============================] - 0s 296us/sample - loss: 5.6528e-04
Epoch 1260/2000
6/6 [==============================] - 0s 239us/sample - loss: 5.5361e-04
Epoch 1261/2000
6/6 [==============================] - 0s 300us/sample - loss: 5.4209e-04
Epoch 1262/2000
6/6 [==============================] - 0s 287us/sample - loss: 5.3111e-04
Epoch 1263

6/6 [==============================] - 0s 474us/sample - loss: 9.5459e-05
Epoch 1344/2000
6/6 [==============================] - 0s 456us/sample - loss: 9.3402e-05
Epoch 1345/2000
6/6 [==============================] - 0s 446us/sample - loss: 9.1387e-05
Epoch 1346/2000
6/6 [==============================] - 0s 463us/sample - loss: 8.9420e-05
Epoch 1347/2000
6/6 [==============================] - 0s 459us/sample - loss: 8.7414e-05
Epoch 1348/2000
6/6 [==============================] - 0s 438us/sample - loss: 8.5648e-05
Epoch 1349/2000
6/6 [==============================] - 0s 502us/sample - loss: 8.3833e-05
Epoch 1350/2000
6/6 [==============================] - 0s 519us/sample - loss: 8.2016e-05
Epoch 1351/2000
6/6 [==============================] - 0s 495us/sample - loss: 8.0302e-05
Epoch 1352/2000
6/6 [==============================] - 0s 301us/sample - loss: 7.8475e-05
Epoch 1353/2000
6/6 [==============================] - 0s 578us/sample - loss: 7.6693e-05
Epoch 1354/2000
6/6 [=====

Epoch 1435/2000
6/6 [==============================] - 0s 259us/sample - loss: 1.1875e-05
Epoch 1436/2000
6/6 [==============================] - 0s 235us/sample - loss: 1.1580e-05
Epoch 1437/2000
6/6 [==============================] - 0s 230us/sample - loss: 1.1323e-05
Epoch 1438/2000
6/6 [==============================] - 0s 218us/sample - loss: 1.1080e-05
Epoch 1439/2000
6/6 [==============================] - 0s 216us/sample - loss: 1.0810e-05
Epoch 1440/2000
6/6 [==============================] - 0s 230us/sample - loss: 1.0546e-05
Epoch 1441/2000
6/6 [==============================] - 0s 207us/sample - loss: 1.0290e-05
Epoch 1442/2000
6/6 [==============================] - 0s 260us/sample - loss: 1.0061e-05
Epoch 1443/2000
6/6 [==============================] - 0s 205us/sample - loss: 9.8174e-06
Epoch 1444/2000
6/6 [==============================] - 0s 216us/sample - loss: 9.6059e-06
Epoch 1445/2000
6/6 [==============================] - 0s 217us/sample - loss: 9.3942e-06
Epoch 1446

Epoch 1526/2000
6/6 [==============================] - 0s 371us/sample - loss: 1.2915e-06
Epoch 1527/2000
6/6 [==============================] - 0s 330us/sample - loss: 1.2589e-06
Epoch 1528/2000
6/6 [==============================] - 0s 295us/sample - loss: 1.2323e-06
Epoch 1529/2000
6/6 [==============================] - 0s 311us/sample - loss: 1.2028e-06
Epoch 1530/2000
6/6 [==============================] - 0s 345us/sample - loss: 1.1712e-06
Epoch 1531/2000
6/6 [==============================] - 0s 381us/sample - loss: 1.1412e-06
Epoch 1532/2000
6/6 [==============================] - 0s 295us/sample - loss: 1.1133e-06
Epoch 1533/2000
6/6 [==============================] - 0s 300us/sample - loss: 1.0920e-06
Epoch 1534/2000
6/6 [==============================] - 0s 353us/sample - loss: 1.0602e-06
Epoch 1535/2000
6/6 [==============================] - 0s 331us/sample - loss: 1.0356e-06
Epoch 1536/2000
6/6 [==============================] - 0s 448us/sample - loss: 1.0121e-06
Epoch 1537

6/6 [==============================] - 0s 333us/sample - loss: 1.2097e-07
Epoch 1618/2000
6/6 [==============================] - 0s 376us/sample - loss: 1.2094e-07
Epoch 1619/2000
6/6 [==============================] - 0s 559us/sample - loss: 1.1724e-07
Epoch 1620/2000
6/6 [==============================] - 0s 512us/sample - loss: 1.1317e-07
Epoch 1621/2000
6/6 [==============================] - 0s 417us/sample - loss: 1.1002e-07
Epoch 1622/2000
6/6 [==============================] - 0s 321us/sample - loss: 1.0874e-07
Epoch 1623/2000
6/6 [==============================] - 0s 322us/sample - loss: 1.0651e-07
Epoch 1624/2000
6/6 [==============================] - 0s 534us/sample - loss: 1.0352e-07
Epoch 1625/2000
6/6 [==============================] - 0s 478us/sample - loss: 1.0191e-07
Epoch 1626/2000
6/6 [==============================] - 0s 276us/sample - loss: 9.8288e-08
Epoch 1627/2000
6/6 [==============================] - 0s 259us/sample - loss: 9.5446e-08
Epoch 1628/2000
6/6 [=====

Epoch 1709/2000
6/6 [==============================] - 0s 451us/sample - loss: 1.0904e-08
Epoch 1710/2000
6/6 [==============================] - 0s 492us/sample - loss: 1.0480e-08
Epoch 1711/2000
6/6 [==============================] - 0s 590us/sample - loss: 1.0482e-08
Epoch 1712/2000
6/6 [==============================] - 0s 570us/sample - loss: 1.0043e-08
Epoch 1713/2000
6/6 [==============================] - 0s 501us/sample - loss: 1.0034e-08
Epoch 1714/2000
6/6 [==============================] - 0s 694us/sample - loss: 9.3545e-09
Epoch 1715/2000
6/6 [==============================] - 0s 1ms/sample - loss: 9.2283e-09
Epoch 1716/2000
6/6 [==============================] - 0s 2ms/sample - loss: 8.8039e-09
Epoch 1717/2000
6/6 [==============================] - 0s 684us/sample - loss: 8.7166e-09
Epoch 1718/2000
6/6 [==============================] - 0s 592us/sample - loss: 8.5784e-09
Epoch 1719/2000
6/6 [==============================] - 0s 924us/sample - loss: 8.3868e-09
Epoch 1720/200

6/6 [==============================] - 0s 510us/sample - loss: 8.4886e-10
Epoch 1801/2000
6/6 [==============================] - 0s 427us/sample - loss: 7.5912e-10
Epoch 1802/2000
6/6 [==============================] - 0s 373us/sample - loss: 7.6155e-10
Epoch 1803/2000
6/6 [==============================] - 0s 453us/sample - loss: 7.6155e-10
Epoch 1804/2000
6/6 [==============================] - 0s 310us/sample - loss: 7.1304e-10
Epoch 1805/2000
6/6 [==============================] - 0s 482us/sample - loss: 7.1304e-10
Epoch 1806/2000
6/6 [==============================] - 0s 450us/sample - loss: 7.1304e-10
Epoch 1807/2000
6/6 [==============================] - 0s 394us/sample - loss: 6.4513e-10
Epoch 1808/2000
6/6 [==============================] - 0s 657us/sample - loss: 6.4513e-10
Epoch 1809/2000
6/6 [==============================] - 0s 336us/sample - loss: 6.3543e-10
Epoch 1810/2000
6/6 [==============================] - 0s 535us/sample - loss: 6.3543e-10
Epoch 1811/2000
6/6 [=====

Epoch 1892/2000
6/6 [==============================] - 0s 328us/sample - loss: 4.4868e-10
Epoch 1893/2000
6/6 [==============================] - 0s 293us/sample - loss: 4.4868e-10
Epoch 1894/2000
6/6 [==============================] - 0s 260us/sample - loss: 4.4868e-10
Epoch 1895/2000
6/6 [==============================] - 0s 275us/sample - loss: 4.4868e-10
Epoch 1896/2000
6/6 [==============================] - 0s 280us/sample - loss: 4.9719e-10
Epoch 1897/2000
6/6 [==============================] - 0s 359us/sample - loss: 5.2629e-10
Epoch 1898/2000
6/6 [==============================] - 0s 305us/sample - loss: 5.2629e-10
Epoch 1899/2000
6/6 [==============================] - 0s 255us/sample - loss: 5.2629e-10
Epoch 1900/2000
6/6 [==============================] - 0s 259us/sample - loss: 5.2629e-10
Epoch 1901/2000
6/6 [==============================] - 0s 291us/sample - loss: 5.2629e-10
Epoch 1902/2000
6/6 [==============================] - 0s 294us/sample - loss: 5.2629e-10
Epoch 1903

6/6 [==============================] - 0s 395us/sample - loss: 4.2201e-10
Epoch 1984/2000
6/6 [==============================] - 0s 340us/sample - loss: 4.2201e-10
Epoch 1985/2000
6/6 [==============================] - 0s 305us/sample - loss: 4.2201e-10
Epoch 1986/2000
6/6 [==============================] - 0s 323us/sample - loss: 4.2201e-10
Epoch 1987/2000
6/6 [==============================] - 0s 268us/sample - loss: 4.2201e-10
Epoch 1988/2000
6/6 [==============================] - 0s 387us/sample - loss: 4.2201e-10
Epoch 1989/2000
6/6 [==============================] - 0s 303us/sample - loss: 3.9290e-10
Epoch 1990/2000
6/6 [==============================] - 0s 314us/sample - loss: 3.9290e-10
Epoch 1991/2000
6/6 [==============================] - 0s 310us/sample - loss: 3.9290e-10
Epoch 1992/2000
6/6 [==============================] - 0s 535us/sample - loss: 4.0260e-10
Epoch 1993/2000
6/6 [==============================] - 0s 370us/sample - loss: 4.0260e-10
Epoch 1994/2000
6/6 [=====

In [5]:
# demonstrate prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape(1, n_steps)
print(x_input)
print(x_input.shape)
yhat = model.predict(x_input, verbose=True)
print(yhat)
print(yhat.shape)

[[70 80 90]]
(1, 3)
1/1 [==============================] - 0s 64ms/sample
[[101.70083]]
(1, 1)


### Multivariate multistep MLP Models

In [6]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out-1
        # check if we are beyond the dataset
        if out_end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
# define input sequence
in_seq1 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = np.array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = np.array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns
dataset = np.hstack((in_seq1, in_seq2, out_seq))
print(dataset)
print(dataset.shape)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]
(9, 3)


In [7]:
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 2) (6, 2)
[[10 15]
 [20 25]
 [30 35]] [65 85]
[[20 25]
 [30 35]
 [40 45]] [ 85 105]
[[30 35]
 [40 45]
 [50 55]] [105 125]
[[40 45]
 [50 55]
 [60 65]] [125 145]
[[50 55]
 [60 65]
 [70 75]] [145 165]
[[60 65]
 [70 75]
 [80 85]] [165 185]


In [8]:
# flatten input
n_input = X.shape[1] * X.shape[2]
X = X.reshape((X.shape[0], n_input))
print(X)
print(X.shape)

[[10 15 20 25 30 35]
 [20 25 30 35 40 45]
 [30 35 40 45 50 55]
 [40 45 50 55 60 65]
 [50 55 60 65 70 75]
 [60 65 70 75 80 85]]
(6, 6)


In [9]:
# define model
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=n_input))
model.add(Dense(units=n_steps_out))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(x=X, y=y, epochs=2000, verbose=True)

Train on 6 samples
Epoch 1/2000
6/6 [==============================] - 0s 57ms/sample - loss: 15730.6943
Epoch 2/2000
6/6 [==============================] - 0s 239us/sample - loss: 15302.2627
Epoch 3/2000
6/6 [==============================] - 0s 233us/sample - loss: 14880.1416
Epoch 4/2000
6/6 [==============================] - 0s 225us/sample - loss: 14465.3975
Epoch 5/2000
6/6 [==============================] - 0s 231us/sample - loss: 14057.1592
Epoch 6/2000
6/6 [==============================] - 0s 256us/sample - loss: 13655.3438
Epoch 7/2000
6/6 [==============================] - 0s 249us/sample - loss: 13260.2920
Epoch 8/2000
6/6 [==============================] - 0s 247us/sample - loss: 12871.7549
Epoch 9/2000
6/6 [==============================] - 0s 254us/sample - loss: 12490.3945
Epoch 10/2000
6/6 [==============================] - 0s 261us/sample - loss: 12116.0967
Epoch 11/2000
6/6 [==============================] - 0s 282us/sample - loss: 11748.7510
Epoch 12/2000
6/6 [====

Epoch 96/2000
6/6 [==============================] - 0s 262us/sample - loss: 120.1947
Epoch 97/2000
6/6 [==============================] - 0s 266us/sample - loss: 117.6157
Epoch 98/2000
6/6 [==============================] - 0s 317us/sample - loss: 115.3406
Epoch 99/2000
6/6 [==============================] - 0s 337us/sample - loss: 113.3361
Epoch 100/2000
6/6 [==============================] - 0s 356us/sample - loss: 111.5723
Epoch 101/2000
6/6 [==============================] - 0s 357us/sample - loss: 110.0221
Epoch 102/2000
6/6 [==============================] - 0s 337us/sample - loss: 108.6627
Epoch 103/2000
6/6 [==============================] - 0s 355us/sample - loss: 107.4801
Epoch 104/2000
6/6 [==============================] - 0s 331us/sample - loss: 106.4448
Epoch 105/2000
6/6 [==============================] - 0s 364us/sample - loss: 105.5401
Epoch 106/2000
6/6 [==============================] - 0s 327us/sample - loss: 104.7508
Epoch 107/2000
6/6 [===========================

Epoch 191/2000
6/6 [==============================] - 0s 276us/sample - loss: 96.1189
Epoch 192/2000
6/6 [==============================] - 0s 329us/sample - loss: 96.0593
Epoch 193/2000
6/6 [==============================] - 0s 286us/sample - loss: 95.9996
Epoch 194/2000
6/6 [==============================] - 0s 276us/sample - loss: 95.9397
Epoch 195/2000
6/6 [==============================] - 0s 281us/sample - loss: 95.8797
Epoch 196/2000
6/6 [==============================] - 0s 280us/sample - loss: 95.8197
Epoch 197/2000
6/6 [==============================] - 0s 320us/sample - loss: 95.7595
Epoch 198/2000
6/6 [==============================] - 0s 296us/sample - loss: 95.6991
Epoch 199/2000
6/6 [==============================] - 0s 296us/sample - loss: 95.6388
Epoch 200/2000
6/6 [==============================] - 0s 268us/sample - loss: 95.5783
Epoch 201/2000
6/6 [==============================] - 0s 273us/sample - loss: 95.5190
Epoch 202/2000
6/6 [==============================] - 

Epoch 287/2000
6/6 [==============================] - 0s 264us/sample - loss: 90.6640
Epoch 288/2000
6/6 [==============================] - 0s 266us/sample - loss: 90.6079
Epoch 289/2000
6/6 [==============================] - 0s 348us/sample - loss: 90.5518
Epoch 290/2000
6/6 [==============================] - 0s 261us/sample - loss: 90.4956
Epoch 291/2000
6/6 [==============================] - 0s 284us/sample - loss: 90.4393
Epoch 292/2000
6/6 [==============================] - 0s 310us/sample - loss: 90.3829
Epoch 293/2000
6/6 [==============================] - 0s 284us/sample - loss: 90.3267
Epoch 294/2000
6/6 [==============================] - 0s 254us/sample - loss: 90.2700
Epoch 295/2000
6/6 [==============================] - 0s 291us/sample - loss: 90.2135
Epoch 296/2000
6/6 [==============================] - 0s 347us/sample - loss: 90.1570
Epoch 297/2000
6/6 [==============================] - 0s 268us/sample - loss: 90.1002
Epoch 298/2000
6/6 [==============================] - 

Epoch 383/2000
6/6 [==============================] - 0s 328us/sample - loss: 85.3619
Epoch 384/2000
6/6 [==============================] - 0s 534us/sample - loss: 85.3091
Epoch 385/2000
6/6 [==============================] - 0s 401us/sample - loss: 85.2562
Epoch 386/2000
6/6 [==============================] - 0s 306us/sample - loss: 85.2033
Epoch 387/2000
6/6 [==============================] - 0s 326us/sample - loss: 85.1504
Epoch 388/2000
6/6 [==============================] - 0s 510us/sample - loss: 85.0974
Epoch 389/2000
6/6 [==============================] - 0s 470us/sample - loss: 85.0442
Epoch 390/2000
6/6 [==============================] - 0s 375us/sample - loss: 84.9911
Epoch 391/2000
6/6 [==============================] - 0s 611us/sample - loss: 84.9381
Epoch 392/2000
6/6 [==============================] - 0s 343us/sample - loss: 84.8848
Epoch 393/2000
6/6 [==============================] - 0s 370us/sample - loss: 84.8316
Epoch 394/2000
6/6 [==============================] - 

Epoch 479/2000
6/6 [==============================] - 0s 290us/sample - loss: 80.1536
Epoch 480/2000
6/6 [==============================] - 0s 302us/sample - loss: 80.0991
Epoch 481/2000
6/6 [==============================] - 0s 344us/sample - loss: 80.0444
Epoch 482/2000
6/6 [==============================] - 0s 293us/sample - loss: 79.9897
Epoch 483/2000
6/6 [==============================] - 0s 296us/sample - loss: 79.9349
Epoch 484/2000
6/6 [==============================] - 0s 289us/sample - loss: 79.8802
Epoch 485/2000
6/6 [==============================] - 0s 270us/sample - loss: 79.8254
Epoch 486/2000
6/6 [==============================] - 0s 335us/sample - loss: 79.7705
Epoch 487/2000
6/6 [==============================] - 0s 280us/sample - loss: 79.7156
Epoch 488/2000
6/6 [==============================] - 0s 313us/sample - loss: 79.6607
Epoch 489/2000
6/6 [==============================] - 0s 341us/sample - loss: 79.6058
Epoch 490/2000
6/6 [==============================] - 

Epoch 575/2000
6/6 [==============================] - 0s 300us/sample - loss: 74.7612
Epoch 576/2000
6/6 [==============================] - 0s 269us/sample - loss: 74.7036
Epoch 577/2000
6/6 [==============================] - 0s 268us/sample - loss: 74.6459
Epoch 578/2000
6/6 [==============================] - 0s 353us/sample - loss: 74.5883
Epoch 579/2000
6/6 [==============================] - 0s 301us/sample - loss: 74.5307
Epoch 580/2000
6/6 [==============================] - 0s 266us/sample - loss: 74.4730
Epoch 581/2000
6/6 [==============================] - 0s 305us/sample - loss: 74.4154
Epoch 582/2000
6/6 [==============================] - 0s 273us/sample - loss: 74.3576
Epoch 583/2000
6/6 [==============================] - 0s 252us/sample - loss: 74.2999
Epoch 584/2000
6/6 [==============================] - 0s 279us/sample - loss: 74.2421
Epoch 585/2000
6/6 [==============================] - 0s 303us/sample - loss: 74.1842
Epoch 586/2000
6/6 [==============================] - 

Epoch 671/2000
6/6 [==============================] - 0s 621us/sample - loss: 69.2040
Epoch 672/2000
6/6 [==============================] - 0s 384us/sample - loss: 69.1478
Epoch 673/2000
6/6 [==============================] - 0s 504us/sample - loss: 69.0917
Epoch 674/2000
6/6 [==============================] - 0s 466us/sample - loss: 69.0356
Epoch 675/2000
6/6 [==============================] - 0s 468us/sample - loss: 68.9793
Epoch 676/2000
6/6 [==============================] - 0s 343us/sample - loss: 68.9232
Epoch 677/2000
6/6 [==============================] - 0s 360us/sample - loss: 68.8669
Epoch 678/2000
6/6 [==============================] - 0s 551us/sample - loss: 68.8107
Epoch 679/2000
6/6 [==============================] - 0s 545us/sample - loss: 68.7544
Epoch 680/2000
6/6 [==============================] - 0s 445us/sample - loss: 68.6982
Epoch 681/2000
6/6 [==============================] - 0s 415us/sample - loss: 68.6419
Epoch 682/2000
6/6 [==============================] - 

Epoch 767/2000
6/6 [==============================] - 0s 534us/sample - loss: 63.7411
Epoch 768/2000
6/6 [==============================] - 0s 391us/sample - loss: 63.6836
Epoch 769/2000
6/6 [==============================] - 0s 691us/sample - loss: 63.6260
Epoch 770/2000
6/6 [==============================] - 0s 512us/sample - loss: 63.5684
Epoch 771/2000
6/6 [==============================] - 0s 331us/sample - loss: 63.5106
Epoch 772/2000
6/6 [==============================] - 0s 528us/sample - loss: 63.4531
Epoch 773/2000
6/6 [==============================] - 0s 638us/sample - loss: 63.3955
Epoch 774/2000
6/6 [==============================] - 0s 546us/sample - loss: 63.3379
Epoch 775/2000
6/6 [==============================] - 0s 407us/sample - loss: 63.2802
Epoch 776/2000
6/6 [==============================] - 0s 614us/sample - loss: 63.2224
Epoch 777/2000
6/6 [==============================] - 0s 354us/sample - loss: 63.1648
Epoch 778/2000
6/6 [==============================] - 

Epoch 863/2000
6/6 [==============================] - 0s 269us/sample - loss: 58.1726
Epoch 864/2000
6/6 [==============================] - 0s 267us/sample - loss: 58.1142
Epoch 865/2000
6/6 [==============================] - 0s 281us/sample - loss: 58.0560
Epoch 866/2000
6/6 [==============================] - 0s 251us/sample - loss: 57.9976
Epoch 867/2000
6/6 [==============================] - 0s 297us/sample - loss: 57.9392
Epoch 868/2000
6/6 [==============================] - 0s 295us/sample - loss: 57.8809
Epoch 869/2000
6/6 [==============================] - 0s 296us/sample - loss: 57.8225
Epoch 870/2000
6/6 [==============================] - 0s 290us/sample - loss: 57.7642
Epoch 871/2000
6/6 [==============================] - 0s 274us/sample - loss: 57.7058
Epoch 872/2000
6/6 [==============================] - 0s 312us/sample - loss: 57.6475
Epoch 873/2000
6/6 [==============================] - 0s 297us/sample - loss: 57.5891
Epoch 874/2000
6/6 [==============================] - 

Epoch 959/2000
6/6 [==============================] - 0s 414us/sample - loss: 52.5643
Epoch 960/2000
6/6 [==============================] - 0s 1ms/sample - loss: 52.5059
Epoch 961/2000
6/6 [==============================] - 0s 498us/sample - loss: 52.4475
Epoch 962/2000
6/6 [==============================] - 0s 1ms/sample - loss: 52.3891
Epoch 963/2000
6/6 [==============================] - 0s 444us/sample - loss: 52.3307
Epoch 964/2000
6/6 [==============================] - 0s 309us/sample - loss: 52.2723
Epoch 965/2000
6/6 [==============================] - 0s 496us/sample - loss: 52.2139
Epoch 966/2000
6/6 [==============================] - 0s 479us/sample - loss: 52.1556
Epoch 967/2000
6/6 [==============================] - 0s 390us/sample - loss: 52.0971
Epoch 968/2000
6/6 [==============================] - 0s 336us/sample - loss: 52.0388
Epoch 969/2000
6/6 [==============================] - 0s 369us/sample - loss: 51.9804
Epoch 970/2000
6/6 [==============================] - 0s 4

Epoch 1054/2000
6/6 [==============================] - 0s 517us/sample - loss: 47.0381
Epoch 1055/2000
6/6 [==============================] - 0s 331us/sample - loss: 46.9802
Epoch 1056/2000
6/6 [==============================] - 0s 320us/sample - loss: 46.9224
Epoch 1057/2000
6/6 [==============================] - 0s 491us/sample - loss: 46.8646
Epoch 1058/2000
6/6 [==============================] - 0s 432us/sample - loss: 46.8068
Epoch 1059/2000
6/6 [==============================] - 0s 391us/sample - loss: 46.7490
Epoch 1060/2000
6/6 [==============================] - 0s 439us/sample - loss: 46.6912
Epoch 1061/2000
6/6 [==============================] - 0s 413us/sample - loss: 46.6335
Epoch 1062/2000
6/6 [==============================] - 0s 410us/sample - loss: 46.5757
Epoch 1063/2000
6/6 [==============================] - 0s 347us/sample - loss: 46.5179
Epoch 1064/2000
6/6 [==============================] - 0s 279us/sample - loss: 46.4602
Epoch 1065/2000
6/6 [======================

6/6 [==============================] - 0s 400us/sample - loss: 41.6539
Epoch 1149/2000
6/6 [==============================] - 0s 369us/sample - loss: 41.5974
Epoch 1150/2000
6/6 [==============================] - 0s 310us/sample - loss: 41.5407
Epoch 1151/2000
6/6 [==============================] - 0s 322us/sample - loss: 41.4842
Epoch 1152/2000
6/6 [==============================] - 0s 577us/sample - loss: 41.4276
Epoch 1153/2000
6/6 [==============================] - 0s 431us/sample - loss: 41.3710
Epoch 1154/2000
6/6 [==============================] - 0s 428us/sample - loss: 41.3145
Epoch 1155/2000
6/6 [==============================] - 0s 461us/sample - loss: 41.2581
Epoch 1156/2000
6/6 [==============================] - 0s 611us/sample - loss: 41.2015
Epoch 1157/2000
6/6 [==============================] - 0s 501us/sample - loss: 41.1451
Epoch 1158/2000
6/6 [==============================] - 0s 367us/sample - loss: 41.0886
Epoch 1159/2000
6/6 [==============================] - 0s 4

Epoch 1243/2000
6/6 [==============================] - 0s 313us/sample - loss: 36.3598
Epoch 1244/2000
6/6 [==============================] - 0s 661us/sample - loss: 36.3051
Epoch 1245/2000
6/6 [==============================] - 0s 431us/sample - loss: 36.2505
Epoch 1246/2000
6/6 [==============================] - 0s 377us/sample - loss: 36.1957
Epoch 1247/2000
6/6 [==============================] - 0s 318us/sample - loss: 36.1411
Epoch 1248/2000
6/6 [==============================] - 0s 495us/sample - loss: 36.0866
Epoch 1249/2000
6/6 [==============================] - 0s 448us/sample - loss: 36.0319
Epoch 1250/2000
6/6 [==============================] - 0s 362us/sample - loss: 35.9773
Epoch 1251/2000
6/6 [==============================] - 0s 434us/sample - loss: 35.9228
Epoch 1252/2000
6/6 [==============================] - 0s 525us/sample - loss: 35.8683
Epoch 1253/2000
6/6 [==============================] - 0s 478us/sample - loss: 35.8137
Epoch 1254/2000
6/6 [======================

Epoch 1337/2000
6/6 [==============================] - 0s 503us/sample - loss: 31.3298
Epoch 1338/2000
6/6 [==============================] - 0s 369us/sample - loss: 31.2775
Epoch 1339/2000
6/6 [==============================] - 0s 419us/sample - loss: 31.2254
Epoch 1340/2000
6/6 [==============================] - 0s 581us/sample - loss: 31.1734
Epoch 1341/2000
6/6 [==============================] - 0s 610us/sample - loss: 31.1213
Epoch 1342/2000
6/6 [==============================] - 0s 472us/sample - loss: 31.0692
Epoch 1343/2000
6/6 [==============================] - 0s 629us/sample - loss: 31.0172
Epoch 1344/2000
6/6 [==============================] - 0s 844us/sample - loss: 30.9652
Epoch 1345/2000
6/6 [==============================] - 0s 364us/sample - loss: 30.9133
Epoch 1346/2000
6/6 [==============================] - 0s 587us/sample - loss: 30.8614
Epoch 1347/2000
6/6 [==============================] - 0s 555us/sample - loss: 30.8094
Epoch 1348/2000
6/6 [======================

Epoch 1432/2000
6/6 [==============================] - 0s 479us/sample - loss: 26.5204
Epoch 1433/2000
6/6 [==============================] - 0s 542us/sample - loss: 26.4714
Epoch 1434/2000
6/6 [==============================] - 0s 324us/sample - loss: 26.4226
Epoch 1435/2000
6/6 [==============================] - 0s 368us/sample - loss: 26.3737
Epoch 1436/2000
6/6 [==============================] - 0s 357us/sample - loss: 26.3249
Epoch 1437/2000
6/6 [==============================] - 0s 435us/sample - loss: 26.2762
Epoch 1438/2000
6/6 [==============================] - 0s 321us/sample - loss: 26.2274
Epoch 1439/2000
6/6 [==============================] - 0s 522us/sample - loss: 26.1787
Epoch 1440/2000
6/6 [==============================] - 0s 546us/sample - loss: 26.1300
Epoch 1441/2000
6/6 [==============================] - 0s 427us/sample - loss: 26.0813
Epoch 1442/2000
6/6 [==============================] - 0s 373us/sample - loss: 26.0328
Epoch 1443/2000
6/6 [======================

6/6 [==============================] - 0s 678us/sample - loss: 22.0940
Epoch 1527/2000
6/6 [==============================] - 0s 317us/sample - loss: 22.0488
Epoch 1528/2000
6/6 [==============================] - 0s 525us/sample - loss: 22.0038
Epoch 1529/2000
6/6 [==============================] - 0s 559us/sample - loss: 21.9587
Epoch 1530/2000
6/6 [==============================] - 0s 351us/sample - loss: 21.9137
Epoch 1531/2000
6/6 [==============================] - 0s 437us/sample - loss: 21.8688
Epoch 1532/2000
6/6 [==============================] - 0s 427us/sample - loss: 21.8239
Epoch 1533/2000
6/6 [==============================] - 0s 464us/sample - loss: 21.7791
Epoch 1534/2000
6/6 [==============================] - 0s 395us/sample - loss: 21.7342
Epoch 1535/2000
6/6 [==============================] - 0s 573us/sample - loss: 21.6895
Epoch 1536/2000
6/6 [==============================] - 0s 560us/sample - loss: 21.6447
Epoch 1537/2000
6/6 [==============================] - 0s 5

Epoch 1621/2000
6/6 [==============================] - 0s 348us/sample - loss: 18.0120
Epoch 1622/2000
6/6 [==============================] - 0s 591us/sample - loss: 17.9714
Epoch 1623/2000
6/6 [==============================] - 0s 575us/sample - loss: 17.9307
Epoch 1624/2000
6/6 [==============================] - 0s 524us/sample - loss: 17.8902
Epoch 1625/2000
6/6 [==============================] - 0s 640us/sample - loss: 17.8496
Epoch 1626/2000
6/6 [==============================] - 0s 594us/sample - loss: 17.8091
Epoch 1627/2000
6/6 [==============================] - 0s 469us/sample - loss: 17.7686
Epoch 1628/2000
6/6 [==============================] - 0s 528us/sample - loss: 17.7282
Epoch 1629/2000
6/6 [==============================] - 0s 674us/sample - loss: 17.6878
Epoch 1630/2000
6/6 [==============================] - 0s 333us/sample - loss: 17.6475
Epoch 1631/2000
6/6 [==============================] - 0s 408us/sample - loss: 17.6073
Epoch 1632/2000
6/6 [======================

6/6 [==============================] - 0s 388us/sample - loss: 14.4062
Epoch 1716/2000
6/6 [==============================] - 0s 424us/sample - loss: 14.3704
Epoch 1717/2000
6/6 [==============================] - 0s 361us/sample - loss: 14.3344
Epoch 1718/2000
6/6 [==============================] - 0s 397us/sample - loss: 14.2986
Epoch 1719/2000
6/6 [==============================] - 0s 448us/sample - loss: 14.2628
Epoch 1720/2000
6/6 [==============================] - 0s 503us/sample - loss: 14.2271
Epoch 1721/2000
6/6 [==============================] - 0s 380us/sample - loss: 14.1915
Epoch 1722/2000
6/6 [==============================] - 0s 299us/sample - loss: 14.1559
Epoch 1723/2000
6/6 [==============================] - 0s 357us/sample - loss: 14.1204
Epoch 1724/2000
6/6 [==============================] - 0s 470us/sample - loss: 14.0848
Epoch 1725/2000
6/6 [==============================] - 0s 438us/sample - loss: 14.0494
Epoch 1726/2000
6/6 [==============================] - 0s 3

Epoch 1810/2000
6/6 [==============================] - 0s 382us/sample - loss: 11.2310
Epoch 1811/2000
6/6 [==============================] - 0s 340us/sample - loss: 11.2001
Epoch 1812/2000
6/6 [==============================] - 0s 309us/sample - loss: 11.1693
Epoch 1813/2000
6/6 [==============================] - 0s 350us/sample - loss: 11.1386
Epoch 1814/2000
6/6 [==============================] - 0s 298us/sample - loss: 11.1079
Epoch 1815/2000
6/6 [==============================] - 0s 358us/sample - loss: 11.0773
Epoch 1816/2000
6/6 [==============================] - 0s 282us/sample - loss: 11.0467
Epoch 1817/2000
6/6 [==============================] - 0s 258us/sample - loss: 11.0162
Epoch 1818/2000
6/6 [==============================] - 0s 259us/sample - loss: 10.9857
Epoch 1819/2000
6/6 [==============================] - 0s 354us/sample - loss: 10.9552
Epoch 1820/2000
6/6 [==============================] - 0s 295us/sample - loss: 10.9249
Epoch 1821/2000
6/6 [======================

Epoch 1905/2000
6/6 [==============================] - 0s 363us/sample - loss: 8.5400
Epoch 1906/2000
6/6 [==============================] - 0s 365us/sample - loss: 8.5143
Epoch 1907/2000
6/6 [==============================] - 0s 442us/sample - loss: 8.4886
Epoch 1908/2000
6/6 [==============================] - 0s 496us/sample - loss: 8.4629
Epoch 1909/2000
6/6 [==============================] - 0s 495us/sample - loss: 8.4373
Epoch 1910/2000
6/6 [==============================] - 0s 332us/sample - loss: 8.4118
Epoch 1911/2000
6/6 [==============================] - 0s 511us/sample - loss: 8.3863
Epoch 1912/2000
6/6 [==============================] - 0s 444us/sample - loss: 8.3608
Epoch 1913/2000
6/6 [==============================] - 0s 369us/sample - loss: 8.3354
Epoch 1914/2000
6/6 [==============================] - 0s 295us/sample - loss: 8.3101
Epoch 1915/2000
6/6 [==============================] - 0s 396us/sample - loss: 8.2848
Epoch 1916/2000
6/6 [==============================] -

In [10]:
# demonstrate prediction
x_input = np.array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_input))
print(x_input)
print(x_input.shape)
yhat = model.predict(x_input, verbose=0)
print(yhat)
print(yhat.shape)

[[70 75 80 85 90 95]]
(1, 6)
[[185.49835 210.73482]]
(1, 2)
