### Univariate CNN Models
1. Data Preparation
2. CNN Model

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Conv1D
from tensorflow.keras.layers import MaxPooling1D

In [2]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time step
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)
print("Actual Input")
print(raw_seq)
print("Reshaped Input")
print(X)
print(X.shape)
print("Desried Output")
print(y)
print(y.shape)

Actual Input
[10, 20, 30, 40, 50, 60, 70, 80, 90]
Reshaped Input
[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
(6, 3)
Desried Output
[40 50 60 70 80 90]
(6,)


In [3]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X.shape)

(6, 3, 1)


In [4]:
# define model
model = Sequential()
model.add(Conv1D(
    filters=64, kernel_size=2, activation='relu',
    input_shape=(n_steps, n_features)
))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(units=50, activation='relu'))
model.add(Dense(units=1))
model.compile(optimizer='adam', loss='mse')

In [5]:
# fit model
model.fit(x=X, y=y, epochs=1000, verbose=True)

Train on 6 samples
Epoch 1/1000
6/6 [==============================] - 1s 178ms/sample - loss: 5401.1177
Epoch 2/1000
6/6 [==============================] - 0s 801us/sample - loss: 5162.8125
Epoch 3/1000
6/6 [==============================] - 0s 632us/sample - loss: 4931.1763
Epoch 4/1000
6/6 [==============================] - 0s 361us/sample - loss: 4705.9956
Epoch 5/1000
6/6 [==============================] - 0s 441us/sample - loss: 4484.9194
Epoch 6/1000
6/6 [==============================] - 0s 363us/sample - loss: 4276.4077
Epoch 7/1000
6/6 [==============================] - 0s 322us/sample - loss: 4093.1719
Epoch 8/1000
6/6 [==============================] - 0s 346us/sample - loss: 3916.7791
Epoch 9/1000
6/6 [==============================] - 0s 444us/sample - loss: 3747.4778
Epoch 10/1000
6/6 [==============================] - 0s 705us/sample - loss: 3587.9421
Epoch 11/1000
6/6 [==============================] - 0s 730us/sample - loss: 3439.0857
Epoch 12/1000
6/6 [==============

Epoch 97/1000
6/6 [==============================] - 0s 710us/sample - loss: 16.9688
Epoch 98/1000
6/6 [==============================] - 0s 614us/sample - loss: 16.9539
Epoch 99/1000
6/6 [==============================] - 0s 517us/sample - loss: 16.9640
Epoch 100/1000
6/6 [==============================] - 0s 438us/sample - loss: 16.9914
Epoch 101/1000
6/6 [==============================] - 0s 631us/sample - loss: 17.0295
Epoch 102/1000
6/6 [==============================] - 0s 511us/sample - loss: 17.0724
Epoch 103/1000
6/6 [==============================] - 0s 431us/sample - loss: 17.1155
Epoch 104/1000
6/6 [==============================] - 0s 579us/sample - loss: 17.1550
Epoch 105/1000
6/6 [==============================] - 0s 768us/sample - loss: 17.1881
Epoch 106/1000
6/6 [==============================] - 0s 478us/sample - loss: 17.2131
Epoch 107/1000
6/6 [==============================] - 0s 485us/sample - loss: 17.2288
Epoch 108/1000
6/6 [==============================] - 0s 

Epoch 193/1000
6/6 [==============================] - 0s 481us/sample - loss: 16.0866
Epoch 194/1000
6/6 [==============================] - 0s 666us/sample - loss: 16.0761
Epoch 195/1000
6/6 [==============================] - 0s 597us/sample - loss: 16.0654
Epoch 196/1000
6/6 [==============================] - 0s 546us/sample - loss: 16.0548
Epoch 197/1000
6/6 [==============================] - 0s 532us/sample - loss: 16.0441
Epoch 198/1000
6/6 [==============================] - 0s 617us/sample - loss: 16.0334
Epoch 199/1000
6/6 [==============================] - 0s 465us/sample - loss: 16.0227
Epoch 200/1000
6/6 [==============================] - 0s 440us/sample - loss: 16.0119
Epoch 201/1000
6/6 [==============================] - 0s 395us/sample - loss: 16.0011
Epoch 202/1000
6/6 [==============================] - 0s 618us/sample - loss: 15.9903
Epoch 203/1000
6/6 [==============================] - 0s 442us/sample - loss: 15.9795
Epoch 204/1000
6/6 [==============================] - 

Epoch 289/1000
6/6 [==============================] - 0s 519us/sample - loss: 14.9411
Epoch 290/1000
6/6 [==============================] - 0s 640us/sample - loss: 14.9280
Epoch 291/1000
6/6 [==============================] - 0s 684us/sample - loss: 14.9149
Epoch 292/1000
6/6 [==============================] - 0s 470us/sample - loss: 14.9018
Epoch 293/1000
6/6 [==============================] - 0s 759us/sample - loss: 14.8887
Epoch 294/1000
6/6 [==============================] - 0s 566us/sample - loss: 14.8755
Epoch 295/1000
6/6 [==============================] - 0s 510us/sample - loss: 14.8623
Epoch 296/1000
6/6 [==============================] - 0s 814us/sample - loss: 14.8491
Epoch 297/1000
6/6 [==============================] - 0s 536us/sample - loss: 14.8359
Epoch 298/1000
6/6 [==============================] - 0s 375us/sample - loss: 14.8226
Epoch 299/1000
6/6 [==============================] - 0s 568us/sample - loss: 14.8093
Epoch 300/1000
6/6 [==============================] - 

Epoch 385/1000
6/6 [==============================] - 0s 391us/sample - loss: 13.5823
Epoch 386/1000
6/6 [==============================] - 0s 599us/sample - loss: 13.5671
Epoch 387/1000
6/6 [==============================] - 0s 458us/sample - loss: 13.5519
Epoch 388/1000
6/6 [==============================] - 0s 410us/sample - loss: 13.5367
Epoch 389/1000
6/6 [==============================] - 0s 674us/sample - loss: 13.5214
Epoch 390/1000
6/6 [==============================] - 0s 562us/sample - loss: 13.5061
Epoch 391/1000
6/6 [==============================] - 0s 324us/sample - loss: 13.4907
Epoch 392/1000
6/6 [==============================] - 0s 490us/sample - loss: 13.4754
Epoch 393/1000
6/6 [==============================] - 0s 697us/sample - loss: 13.4600
Epoch 394/1000
6/6 [==============================] - 0s 507us/sample - loss: 13.4446
Epoch 395/1000
6/6 [==============================] - 0s 557us/sample - loss: 13.4291
Epoch 396/1000
6/6 [==============================] - 

Epoch 481/1000
6/6 [==============================] - 0s 399us/sample - loss: 11.9869
Epoch 482/1000
6/6 [==============================] - 0s 440us/sample - loss: 11.9694
Epoch 483/1000
6/6 [==============================] - 0s 366us/sample - loss: 11.9519
Epoch 484/1000
6/6 [==============================] - 0s 442us/sample - loss: 11.9343
Epoch 485/1000
6/6 [==============================] - 0s 394us/sample - loss: 11.9168
Epoch 486/1000
6/6 [==============================] - 0s 498us/sample - loss: 11.8991
Epoch 487/1000
6/6 [==============================] - 0s 363us/sample - loss: 11.8818
Epoch 488/1000
6/6 [==============================] - 0s 349us/sample - loss: 11.8642
Epoch 489/1000
6/6 [==============================] - 0s 505us/sample - loss: 11.8465
Epoch 490/1000
6/6 [==============================] - 0s 458us/sample - loss: 11.8289
Epoch 491/1000
6/6 [==============================] - 0s 397us/sample - loss: 11.8114
Epoch 492/1000
6/6 [==============================] - 

Epoch 577/1000
6/6 [==============================] - 0s 437us/sample - loss: 10.3122
Epoch 578/1000
6/6 [==============================] - 0s 449us/sample - loss: 10.2946
Epoch 579/1000
6/6 [==============================] - 0s 412us/sample - loss: 10.2771
Epoch 580/1000
6/6 [==============================] - 0s 375us/sample - loss: 10.2595
Epoch 581/1000
6/6 [==============================] - 0s 430us/sample - loss: 10.2420
Epoch 582/1000
6/6 [==============================] - 0s 452us/sample - loss: 10.2246
Epoch 583/1000
6/6 [==============================] - 0s 365us/sample - loss: 10.2069
Epoch 584/1000
6/6 [==============================] - 0s 329us/sample - loss: 10.1895
Epoch 585/1000
6/6 [==============================] - 0s 319us/sample - loss: 10.1721
Epoch 586/1000
6/6 [==============================] - 0s 390us/sample - loss: 10.1545
Epoch 587/1000
6/6 [==============================] - 0s 391us/sample - loss: 10.1369
Epoch 588/1000
6/6 [==============================] - 

Epoch 674/1000
6/6 [==============================] - 0s 385us/sample - loss: 8.5904
Epoch 675/1000
6/6 [==============================] - 0s 430us/sample - loss: 8.5727
Epoch 676/1000
6/6 [==============================] - 0s 351us/sample - loss: 8.5549
Epoch 677/1000
6/6 [==============================] - 0s 483us/sample - loss: 8.5371
Epoch 678/1000
6/6 [==============================] - 0s 479us/sample - loss: 8.5191
Epoch 679/1000
6/6 [==============================] - 0s 431us/sample - loss: 8.5009
Epoch 680/1000
6/6 [==============================] - 0s 418us/sample - loss: 8.4826
Epoch 681/1000
6/6 [==============================] - 0s 440us/sample - loss: 8.4656
Epoch 682/1000
6/6 [==============================] - 0s 484us/sample - loss: 8.4480
Epoch 683/1000
6/6 [==============================] - 0s 437us/sample - loss: 8.4295
Epoch 684/1000
6/6 [==============================] - 0s 395us/sample - loss: 8.4111
Epoch 685/1000
6/6 [==============================] - 0s 537us/sa

Epoch 771/1000
6/6 [==============================] - 0s 412us/sample - loss: 6.8562
Epoch 772/1000
6/6 [==============================] - 0s 391us/sample - loss: 6.8382
Epoch 773/1000
6/6 [==============================] - 0s 370us/sample - loss: 6.8203
Epoch 774/1000
6/6 [==============================] - 0s 396us/sample - loss: 6.8024
Epoch 775/1000
6/6 [==============================] - 0s 299us/sample - loss: 6.7844
Epoch 776/1000
6/6 [==============================] - 0s 381us/sample - loss: 6.7673
Epoch 777/1000
6/6 [==============================] - 0s 371us/sample - loss: 6.7497
Epoch 778/1000
6/6 [==============================] - 0s 493us/sample - loss: 6.7319
Epoch 779/1000
6/6 [==============================] - 0s 356us/sample - loss: 6.7135
Epoch 780/1000
6/6 [==============================] - 0s 441us/sample - loss: 6.6957
Epoch 781/1000
6/6 [==============================] - 0s 500us/sample - loss: 6.6782
Epoch 782/1000
6/6 [==============================] - 0s 446us/sa

Epoch 868/1000
6/6 [==============================] - 0s 391us/sample - loss: 5.1699
Epoch 869/1000
6/6 [==============================] - 0s 334us/sample - loss: 5.1527
Epoch 870/1000
6/6 [==============================] - 0s 433us/sample - loss: 5.1348
Epoch 871/1000
6/6 [==============================] - 0s 449us/sample - loss: 5.1183
Epoch 872/1000
6/6 [==============================] - 0s 549us/sample - loss: 5.1017
Epoch 873/1000
6/6 [==============================] - 0s 409us/sample - loss: 5.0853
Epoch 874/1000
6/6 [==============================] - 0s 391us/sample - loss: 5.0685
Epoch 875/1000
6/6 [==============================] - 0s 463us/sample - loss: 5.0517
Epoch 876/1000
6/6 [==============================] - 0s 446us/sample - loss: 5.0346
Epoch 877/1000
6/6 [==============================] - 0s 506us/sample - loss: 5.0178
Epoch 878/1000
6/6 [==============================] - 0s 385us/sample - loss: 5.0004
Epoch 879/1000
6/6 [==============================] - 0s 407us/sa

Epoch 965/1000
6/6 [==============================] - 0s 330us/sample - loss: 3.6162
Epoch 966/1000
6/6 [==============================] - 0s 304us/sample - loss: 3.6013
Epoch 967/1000
6/6 [==============================] - 0s 399us/sample - loss: 3.5856
Epoch 968/1000
6/6 [==============================] - 0s 477us/sample - loss: 3.5702
Epoch 969/1000
6/6 [==============================] - 0s 507us/sample - loss: 3.5563
Epoch 970/1000
6/6 [==============================] - 0s 349us/sample - loss: 3.5419
Epoch 971/1000
6/6 [==============================] - 0s 336us/sample - loss: 3.5267
Epoch 972/1000
6/6 [==============================] - 0s 326us/sample - loss: 3.5108
Epoch 973/1000
6/6 [==============================] - 0s 429us/sample - loss: 3.4960
Epoch 974/1000
6/6 [==============================] - 0s 348us/sample - loss: 3.4819
Epoch 975/1000
6/6 [==============================] - 0s 314us/sample - loss: 3.4673
Epoch 976/1000
6/6 [==============================] - 0s 368us/sa

In [6]:
# demo prediction
x_input = np.array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(tf.cast(x_input, tf.float32), verbose=True)
print(yhat)
print(yhat.shape)

1/1 [==============================] - 0s 68ms/sample
[[103.23618]]
(1, 1)


### Multivariate CNN Models
1. Single step prediction
2. Multi step prediction

In [7]:
# multivariate data preparation
from numpy import array
from numpy import hstack
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))                 
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns                
dataset = hstack((in_seq1, in_seq2, out_seq))
print(dataset)
print(dataset.shape)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]
(9, 3)


In [8]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [9]:
# define model
models = Sequential()
models.add(Conv1D(
    filters=64, kernel_size=2, activation='relu',
    input_shape=(n_steps, n_features)
))
models.add(MaxPooling1D())
models.add(Flatten())
models.add(Dense(units=50, activation='relu'))
models.add(Dense(units=1))
models.compile(optimizer='adam', loss='mse')
# fit model
models.fit(x=X, y=y, epochs=1000, verbose=True)

Train on 7 samples
Epoch 1/1000
7/7 [==============================] - 0s 70ms/sample - loss: 24245.6875
Epoch 2/1000
7/7 [==============================] - 0s 309us/sample - loss: 23293.0000
Epoch 3/1000
7/7 [==============================] - 0s 329us/sample - loss: 22333.8789
Epoch 4/1000
7/7 [==============================] - 0s 362us/sample - loss: 21401.8965
Epoch 5/1000
7/7 [==============================] - 0s 334us/sample - loss: 20526.2793
Epoch 6/1000
7/7 [==============================] - 0s 275us/sample - loss: 19729.9121
Epoch 7/1000
7/7 [==============================] - 0s 263us/sample - loss: 18964.9785
Epoch 8/1000
7/7 [==============================] - 0s 389us/sample - loss: 18257.4082
Epoch 9/1000
7/7 [==============================] - 0s 302us/sample - loss: 17563.0137
Epoch 10/1000
7/7 [==============================] - 0s 283us/sample - loss: 16903.7871
Epoch 11/1000
7/7 [==============================] - 0s 321us/sample - loss: 16261.4219
Epoch 12/1000
7/7 [====

Epoch 96/1000
7/7 [==============================] - 0s 346us/sample - loss: 12.6290
Epoch 97/1000
7/7 [==============================] - 0s 354us/sample - loss: 10.9149
Epoch 98/1000
7/7 [==============================] - 0s 326us/sample - loss: 9.6060
Epoch 99/1000
7/7 [==============================] - 0s 335us/sample - loss: 8.6617
Epoch 100/1000
7/7 [==============================] - 0s 347us/sample - loss: 8.0350
Epoch 101/1000
7/7 [==============================] - 0s 309us/sample - loss: 7.6757
Epoch 102/1000
7/7 [==============================] - 0s 340us/sample - loss: 7.5332
Epoch 103/1000
7/7 [==============================] - 0s 349us/sample - loss: 7.5583
Epoch 104/1000
7/7 [==============================] - 0s 502us/sample - loss: 7.7052
Epoch 105/1000
7/7 [==============================] - 0s 336us/sample - loss: 7.9322
Epoch 106/1000
7/7 [==============================] - 0s 379us/sample - loss: 8.2034
Epoch 107/1000
7/7 [==============================] - 0s 281us/samp

Epoch 193/1000
7/7 [==============================] - 0s 307us/sample - loss: 7.3282
Epoch 194/1000
7/7 [==============================] - 0s 365us/sample - loss: 7.3255
Epoch 195/1000
7/7 [==============================] - 0s 236us/sample - loss: 7.3229
Epoch 196/1000
7/7 [==============================] - 0s 256us/sample - loss: 7.3201
Epoch 197/1000
7/7 [==============================] - 0s 338us/sample - loss: 7.3174
Epoch 198/1000
7/7 [==============================] - 0s 287us/sample - loss: 7.3147
Epoch 199/1000
7/7 [==============================] - 0s 268us/sample - loss: 7.3119
Epoch 200/1000
7/7 [==============================] - 0s 381us/sample - loss: 7.3091
Epoch 201/1000
7/7 [==============================] - 0s 295us/sample - loss: 7.3064
Epoch 202/1000
7/7 [==============================] - 0s 365us/sample - loss: 7.3036
Epoch 203/1000
7/7 [==============================] - 0s 309us/sample - loss: 7.3008
Epoch 204/1000
7/7 [==============================] - 0s 271us/sa

Epoch 290/1000
7/7 [==============================] - 0s 334us/sample - loss: 7.0391
Epoch 291/1000
7/7 [==============================] - 0s 263us/sample - loss: 7.0364
Epoch 292/1000
7/7 [==============================] - 0s 266us/sample - loss: 7.0336
Epoch 293/1000
7/7 [==============================] - 0s 313us/sample - loss: 7.0309
Epoch 294/1000
7/7 [==============================] - 0s 414us/sample - loss: 7.0281
Epoch 295/1000
7/7 [==============================] - 0s 330us/sample - loss: 7.0253
Epoch 296/1000
7/7 [==============================] - 0s 294us/sample - loss: 7.0226
Epoch 297/1000
7/7 [==============================] - 0s 266us/sample - loss: 7.0197
Epoch 298/1000
7/7 [==============================] - 0s 265us/sample - loss: 7.0170
Epoch 299/1000
7/7 [==============================] - 0s 375us/sample - loss: 7.0142
Epoch 300/1000
7/7 [==============================] - 0s 314us/sample - loss: 7.0113
Epoch 301/1000
7/7 [==============================] - 0s 305us/sa

Epoch 387/1000
7/7 [==============================] - 0s 320us/sample - loss: 6.7515
Epoch 388/1000
7/7 [==============================] - 0s 368us/sample - loss: 6.7483
Epoch 389/1000
7/7 [==============================] - 0s 308us/sample - loss: 6.7452
Epoch 390/1000
7/7 [==============================] - 0s 268us/sample - loss: 6.7419
Epoch 391/1000
7/7 [==============================] - 0s 347us/sample - loss: 6.7388
Epoch 392/1000
7/7 [==============================] - 0s 325us/sample - loss: 6.7356
Epoch 393/1000
7/7 [==============================] - 0s 316us/sample - loss: 6.7324
Epoch 394/1000
7/7 [==============================] - 0s 311us/sample - loss: 6.7292
Epoch 395/1000
7/7 [==============================] - 0s 251us/sample - loss: 6.7260
Epoch 396/1000
7/7 [==============================] - 0s 290us/sample - loss: 6.7228
Epoch 397/1000
7/7 [==============================] - 0s 345us/sample - loss: 6.7197
Epoch 398/1000
7/7 [==============================] - 0s 310us/sa

Epoch 484/1000
7/7 [==============================] - 0s 287us/sample - loss: 6.4266
Epoch 485/1000
7/7 [==============================] - 0s 323us/sample - loss: 6.4231
Epoch 486/1000
7/7 [==============================] - 0s 376us/sample - loss: 6.4196
Epoch 487/1000
7/7 [==============================] - 0s 320us/sample - loss: 6.4160
Epoch 488/1000
7/7 [==============================] - 0s 370us/sample - loss: 6.4125
Epoch 489/1000
7/7 [==============================] - 0s 349us/sample - loss: 6.4090
Epoch 490/1000
7/7 [==============================] - 0s 390us/sample - loss: 6.4054
Epoch 491/1000
7/7 [==============================] - 0s 367us/sample - loss: 6.4019
Epoch 492/1000
7/7 [==============================] - 0s 385us/sample - loss: 6.3983
Epoch 493/1000
7/7 [==============================] - 0s 271us/sample - loss: 6.3948
Epoch 494/1000
7/7 [==============================] - 0s 323us/sample - loss: 6.3912
Epoch 495/1000
7/7 [==============================] - 0s 427us/sa

Epoch 581/1000
7/7 [==============================] - 0s 397us/sample - loss: 6.0696
Epoch 582/1000
7/7 [==============================] - 0s 378us/sample - loss: 6.0659
Epoch 583/1000
7/7 [==============================] - 0s 314us/sample - loss: 6.0620
Epoch 584/1000
7/7 [==============================] - 0s 310us/sample - loss: 6.0581
Epoch 585/1000
7/7 [==============================] - 0s 472us/sample - loss: 6.0543
Epoch 586/1000
7/7 [==============================] - 0s 403us/sample - loss: 6.0505
Epoch 587/1000
7/7 [==============================] - 0s 457us/sample - loss: 6.0467
Epoch 588/1000
7/7 [==============================] - 0s 480us/sample - loss: 6.0428
Epoch 589/1000
7/7 [==============================] - 0s 314us/sample - loss: 6.0389
Epoch 590/1000
7/7 [==============================] - 0s 358us/sample - loss: 6.0351
Epoch 591/1000
7/7 [==============================] - 0s 399us/sample - loss: 6.0312
Epoch 592/1000
7/7 [==============================] - 0s 539us/sa

Epoch 678/1000
7/7 [==============================] - 0s 395us/sample - loss: 5.6854
Epoch 679/1000
7/7 [==============================] - 0s 508us/sample - loss: 5.6813
Epoch 680/1000
7/7 [==============================] - 0s 469us/sample - loss: 5.6772
Epoch 681/1000
7/7 [==============================] - 0s 426us/sample - loss: 5.6732
Epoch 682/1000
7/7 [==============================] - 0s 335us/sample - loss: 5.6691
Epoch 683/1000
7/7 [==============================] - 0s 381us/sample - loss: 5.6649
Epoch 684/1000
7/7 [==============================] - 0s 589us/sample - loss: 5.6608
Epoch 685/1000
7/7 [==============================] - 0s 836us/sample - loss: 5.6567
Epoch 686/1000
7/7 [==============================] - 0s 333us/sample - loss: 5.6526
Epoch 687/1000
7/7 [==============================] - 0s 943us/sample - loss: 5.6485
Epoch 688/1000
7/7 [==============================] - 0s 549us/sample - loss: 5.6444
Epoch 689/1000
7/7 [==============================] - 0s 667us/sa

Epoch 775/1000
7/7 [==============================] - 0s 287us/sample - loss: 5.2783
Epoch 776/1000
7/7 [==============================] - 0s 252us/sample - loss: 5.2741
Epoch 777/1000
7/7 [==============================] - 0s 376us/sample - loss: 5.2697
Epoch 778/1000
7/7 [==============================] - 0s 374us/sample - loss: 5.2654
Epoch 779/1000
7/7 [==============================] - 0s 327us/sample - loss: 5.2611
Epoch 780/1000
7/7 [==============================] - 0s 308us/sample - loss: 5.2568
Epoch 781/1000
7/7 [==============================] - 0s 277us/sample - loss: 5.2525
Epoch 782/1000
7/7 [==============================] - 0s 272us/sample - loss: 5.2482
Epoch 783/1000
7/7 [==============================] - 0s 279us/sample - loss: 5.2439
Epoch 784/1000
7/7 [==============================] - 0s 247us/sample - loss: 5.2396
Epoch 785/1000
7/7 [==============================] - 0s 245us/sample - loss: 5.2352
Epoch 786/1000
7/7 [==============================] - 0s 314us/sa

Epoch 872/1000
7/7 [==============================] - 0s 484us/sample - loss: 4.8529
Epoch 873/1000
7/7 [==============================] - 0s 355us/sample - loss: 4.8484
Epoch 874/1000
7/7 [==============================] - 0s 314us/sample - loss: 4.8439
Epoch 875/1000
7/7 [==============================] - 0s 318us/sample - loss: 4.8394
Epoch 876/1000
7/7 [==============================] - 0s 347us/sample - loss: 4.8350
Epoch 877/1000
7/7 [==============================] - 0s 347us/sample - loss: 4.8305
Epoch 878/1000
7/7 [==============================] - 0s 359us/sample - loss: 4.8260
Epoch 879/1000
7/7 [==============================] - 0s 360us/sample - loss: 4.8215
Epoch 880/1000
7/7 [==============================] - 0s 300us/sample - loss: 4.8171
Epoch 881/1000
7/7 [==============================] - 0s 332us/sample - loss: 4.8126
Epoch 882/1000
7/7 [==============================] - 0s 363us/sample - loss: 4.8081
Epoch 883/1000
7/7 [==============================] - 0s 266us/sa

Epoch 969/1000
7/7 [==============================] - 0s 293us/sample - loss: 4.4204
Epoch 970/1000
7/7 [==============================] - 0s 288us/sample - loss: 4.4159
Epoch 971/1000
7/7 [==============================] - 0s 285us/sample - loss: 4.4114
Epoch 972/1000
7/7 [==============================] - 0s 293us/sample - loss: 4.4070
Epoch 973/1000
7/7 [==============================] - 0s 289us/sample - loss: 4.4025
Epoch 974/1000
7/7 [==============================] - 0s 285us/sample - loss: 4.3979
Epoch 975/1000
7/7 [==============================] - 0s 294us/sample - loss: 4.3935
Epoch 976/1000
7/7 [==============================] - 0s 329us/sample - loss: 4.3891
Epoch 977/1000
7/7 [==============================] - 0s 289us/sample - loss: 4.3846
Epoch 978/1000
7/7 [==============================] - 0s 343us/sample - loss: 4.3801
Epoch 979/1000
7/7 [==============================] - 0s 294us/sample - loss: 4.3756
Epoch 980/1000
7/7 [==============================] - 0s 296us/sa

In [10]:
# demo prediction
x_input = np.array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))
print(x_input)
print(x_input.shape)
yhat = models.predict(tf.cast(x_input, tf.float32), verbose=True)
print(yhat)
print(yhat.shape)

[[[ 80  85]
  [ 90  95]
  [100 105]]]
(1, 3, 2)
1/1 [==============================] - 0s 42ms/sample
[[208.30171]]
(1, 1)


### Multivariate multistep CNN models

In [11]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out-1
        # check if we are beyond the dataset
        if out_end_ix > len(sequences):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1:out_end_ix, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure 
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1)) 
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
print(dataset)
print(dataset.shape)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]
(9, 3)


In [12]:
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# convert into input/output
X, y = split_sequences(dataset, n_steps_in, n_steps_out)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
    print(X[i], y[i])

(6, 3, 2) (6, 2)
[[10 15]
 [20 25]
 [30 35]] [65 85]
[[20 25]
 [30 35]
 [40 45]] [ 85 105]
[[30 35]
 [40 45]
 [50 55]] [105 125]
[[40 45]
 [50 55]
 [60 65]] [125 145]
[[50 55]
 [60 65]
 [70 75]] [145 165]
[[60 65]
 [70 75]
 [80 85]] [165 185]


In [13]:
# define model
models = Sequential()
models.add(Conv1D(
    filters=64, kernel_size=2, activation='relu',
    input_shape=(n_steps_in, n_features)
))
models.add(MaxPooling1D())
models.add(Flatten())
models.add(Dense(units=50, activation='relu'))
models.add(Dense(units=n_steps_out))
models.compile(optimizer='adam', loss='mse')
# fit model
models.fit(x=X, y=y, epochs=2000, verbose=True)

Train on 6 samples
Epoch 1/2000
6/6 [==============================] - 0s 79ms/sample - loss: 15155.4189
Epoch 2/2000
6/6 [==============================] - 0s 314us/sample - loss: 14837.0029
Epoch 3/2000
6/6 [==============================] - 0s 290us/sample - loss: 14493.5635
Epoch 4/2000
6/6 [==============================] - 0s 295us/sample - loss: 14140.6514
Epoch 5/2000
6/6 [==============================] - 0s 339us/sample - loss: 13785.1670
Epoch 6/2000
6/6 [==============================] - 0s 297us/sample - loss: 13430.2031
Epoch 7/2000
6/6 [==============================] - 0s 280us/sample - loss: 13076.2344
Epoch 8/2000
6/6 [==============================] - 0s 292us/sample - loss: 12723.5146
Epoch 9/2000
6/6 [==============================] - 0s 312us/sample - loss: 12372.4775
Epoch 10/2000
6/6 [==============================] - 0s 307us/sample - loss: 12029.2607
Epoch 11/2000
6/6 [==============================] - 0s 316us/sample - loss: 11690.9912
Epoch 12/2000
6/6 [====

Epoch 96/2000
6/6 [==============================] - 0s 518us/sample - loss: 47.8940
Epoch 97/2000
6/6 [==============================] - 0s 424us/sample - loss: 47.8561
Epoch 98/2000
6/6 [==============================] - 0s 388us/sample - loss: 47.9136
Epoch 99/2000
6/6 [==============================] - 0s 599us/sample - loss: 48.0356
Epoch 100/2000
6/6 [==============================] - 0s 416us/sample - loss: 48.1949
Epoch 101/2000
6/6 [==============================] - 0s 648us/sample - loss: 48.3682
Epoch 102/2000
6/6 [==============================] - 0s 407us/sample - loss: 48.5363
Epoch 103/2000
6/6 [==============================] - 0s 485us/sample - loss: 48.6839
Epoch 104/2000
6/6 [==============================] - 0s 455us/sample - loss: 48.7999
Epoch 105/2000
6/6 [==============================] - 0s 458us/sample - loss: 48.8767
Epoch 106/2000
6/6 [==============================] - 0s 737us/sample - loss: 48.9101
Epoch 107/2000
6/6 [==============================] - 0s 5

Epoch 192/2000
6/6 [==============================] - 0s 314us/sample - loss: 45.7255
Epoch 193/2000
6/6 [==============================] - 0s 380us/sample - loss: 45.7112
Epoch 194/2000
6/6 [==============================] - 0s 586us/sample - loss: 45.6969
Epoch 195/2000
6/6 [==============================] - 0s 381us/sample - loss: 45.6827
Epoch 196/2000
6/6 [==============================] - 0s 354us/sample - loss: 45.6683
Epoch 197/2000
6/6 [==============================] - 0s 355us/sample - loss: 45.6539
Epoch 198/2000
6/6 [==============================] - 0s 319us/sample - loss: 45.6396
Epoch 199/2000
6/6 [==============================] - 0s 539us/sample - loss: 45.6251
Epoch 200/2000
6/6 [==============================] - 0s 884us/sample - loss: 45.6106
Epoch 201/2000
6/6 [==============================] - 0s 319us/sample - loss: 45.5961
Epoch 202/2000
6/6 [==============================] - 0s 318us/sample - loss: 45.5817
Epoch 203/2000
6/6 [==============================] - 

Epoch 288/2000
6/6 [==============================] - 0s 645us/sample - loss: 44.2176
Epoch 289/2000
6/6 [==============================] - 0s 1ms/sample - loss: 44.2005
Epoch 290/2000
6/6 [==============================] - 0s 484us/sample - loss: 44.1834
Epoch 291/2000
6/6 [==============================] - 0s 630us/sample - loss: 44.1663
Epoch 292/2000
6/6 [==============================] - 0s 675us/sample - loss: 44.1490
Epoch 293/2000
6/6 [==============================] - 0s 499us/sample - loss: 44.1318
Epoch 294/2000
6/6 [==============================] - 0s 515us/sample - loss: 44.1146
Epoch 295/2000
6/6 [==============================] - 0s 645us/sample - loss: 44.0974
Epoch 296/2000
6/6 [==============================] - 0s 541us/sample - loss: 44.0802
Epoch 297/2000
6/6 [==============================] - 0s 482us/sample - loss: 44.0628
Epoch 298/2000
6/6 [==============================] - 0s 803us/sample - loss: 44.0455
Epoch 299/2000
6/6 [==============================] - 0s

Epoch 384/2000
6/6 [==============================] - 0s 508us/sample - loss: 42.4655
Epoch 385/2000
6/6 [==============================] - 0s 525us/sample - loss: 42.4462
Epoch 386/2000
6/6 [==============================] - 0s 409us/sample - loss: 42.4269
Epoch 387/2000
6/6 [==============================] - 0s 408us/sample - loss: 42.4075
Epoch 388/2000
6/6 [==============================] - 0s 380us/sample - loss: 42.3881
Epoch 389/2000
6/6 [==============================] - 0s 343us/sample - loss: 42.3687
Epoch 390/2000
6/6 [==============================] - 0s 329us/sample - loss: 42.3493
Epoch 391/2000
6/6 [==============================] - 0s 349us/sample - loss: 42.3298
Epoch 392/2000
6/6 [==============================] - 0s 552us/sample - loss: 42.3103
Epoch 393/2000
6/6 [==============================] - 0s 555us/sample - loss: 42.2909
Epoch 394/2000
6/6 [==============================] - 0s 607us/sample - loss: 42.2712
Epoch 395/2000
6/6 [==============================] - 

Epoch 480/2000
6/6 [==============================] - 0s 414us/sample - loss: 40.5214
Epoch 481/2000
6/6 [==============================] - 0s 560us/sample - loss: 40.5002
Epoch 482/2000
6/6 [==============================] - 0s 473us/sample - loss: 40.4791
Epoch 483/2000
6/6 [==============================] - 0s 371us/sample - loss: 40.4580
Epoch 484/2000
6/6 [==============================] - 0s 399us/sample - loss: 40.4368
Epoch 485/2000
6/6 [==============================] - 0s 559us/sample - loss: 40.4155
Epoch 486/2000
6/6 [==============================] - 0s 535us/sample - loss: 40.3944
Epoch 487/2000
6/6 [==============================] - 0s 424us/sample - loss: 40.3731
Epoch 488/2000
6/6 [==============================] - 0s 389us/sample - loss: 40.3519
Epoch 489/2000
6/6 [==============================] - 0s 413us/sample - loss: 40.3306
Epoch 490/2000
6/6 [==============================] - 0s 398us/sample - loss: 40.3093
Epoch 491/2000
6/6 [==============================] - 

Epoch 576/2000
6/6 [==============================] - 0s 315us/sample - loss: 38.4205
Epoch 577/2000
6/6 [==============================] - 0s 287us/sample - loss: 38.3979
Epoch 578/2000
6/6 [==============================] - 0s 323us/sample - loss: 38.3753
Epoch 579/2000
6/6 [==============================] - 0s 348us/sample - loss: 38.3526
Epoch 580/2000
6/6 [==============================] - 0s 350us/sample - loss: 38.3300
Epoch 581/2000
6/6 [==============================] - 0s 334us/sample - loss: 38.3073
Epoch 582/2000
6/6 [==============================] - 0s 327us/sample - loss: 38.2846
Epoch 583/2000
6/6 [==============================] - 0s 349us/sample - loss: 38.2620
Epoch 584/2000
6/6 [==============================] - 0s 325us/sample - loss: 38.2392
Epoch 585/2000
6/6 [==============================] - 0s 295us/sample - loss: 38.2165
Epoch 586/2000
6/6 [==============================] - 0s 336us/sample - loss: 38.1937
Epoch 587/2000
6/6 [==============================] - 

Epoch 672/2000
6/6 [==============================] - 0s 313us/sample - loss: 36.1871
Epoch 673/2000
6/6 [==============================] - 0s 292us/sample - loss: 36.1632
Epoch 674/2000
6/6 [==============================] - 0s 282us/sample - loss: 36.1393
Epoch 675/2000
6/6 [==============================] - 0s 332us/sample - loss: 36.1153
Epoch 676/2000
6/6 [==============================] - 0s 308us/sample - loss: 36.0914
Epoch 677/2000
6/6 [==============================] - 0s 301us/sample - loss: 36.0676
Epoch 678/2000
6/6 [==============================] - 0s 324us/sample - loss: 36.0435
Epoch 679/2000
6/6 [==============================] - 0s 316us/sample - loss: 36.0195
Epoch 680/2000
6/6 [==============================] - 0s 384us/sample - loss: 35.9955
Epoch 681/2000
6/6 [==============================] - 0s 340us/sample - loss: 35.9715
Epoch 682/2000
6/6 [==============================] - 0s 356us/sample - loss: 35.9475
Epoch 683/2000
6/6 [==============================] - 

Epoch 768/2000
6/6 [==============================] - 0s 261us/sample - loss: 33.8367
Epoch 769/2000
6/6 [==============================] - 0s 272us/sample - loss: 33.8117
Epoch 770/2000
6/6 [==============================] - 0s 244us/sample - loss: 33.7865
Epoch 771/2000
6/6 [==============================] - 0s 273us/sample - loss: 33.7614
Epoch 772/2000
6/6 [==============================] - 0s 270us/sample - loss: 33.7363
Epoch 773/2000
6/6 [==============================] - 0s 288us/sample - loss: 33.7112
Epoch 774/2000
6/6 [==============================] - 0s 288us/sample - loss: 33.6861
Epoch 775/2000
6/6 [==============================] - 0s 257us/sample - loss: 33.6610
Epoch 776/2000
6/6 [==============================] - 0s 290us/sample - loss: 33.6358
Epoch 777/2000
6/6 [==============================] - 0s 270us/sample - loss: 33.6107
Epoch 778/2000
6/6 [==============================] - 0s 271us/sample - loss: 33.5855
Epoch 779/2000
6/6 [==============================] - 

Epoch 864/2000
6/6 [==============================] - 0s 253us/sample - loss: 31.3784
Epoch 865/2000
6/6 [==============================] - 0s 269us/sample - loss: 31.3524
Epoch 866/2000
6/6 [==============================] - 0s 319us/sample - loss: 31.3262
Epoch 867/2000
6/6 [==============================] - 0s 300us/sample - loss: 31.3000
Epoch 868/2000
6/6 [==============================] - 0s 290us/sample - loss: 31.2738
Epoch 869/2000
6/6 [==============================] - 0s 273us/sample - loss: 31.2476
Epoch 870/2000
6/6 [==============================] - 0s 269us/sample - loss: 31.2214
Epoch 871/2000
6/6 [==============================] - 0s 295us/sample - loss: 31.1953
Epoch 872/2000
6/6 [==============================] - 0s 279us/sample - loss: 31.1690
Epoch 873/2000
6/6 [==============================] - 0s 288us/sample - loss: 31.1427
Epoch 874/2000
6/6 [==============================] - 0s 280us/sample - loss: 31.1165
Epoch 875/2000
6/6 [==============================] - 

Epoch 960/2000
6/6 [==============================] - 0s 260us/sample - loss: 28.8173
Epoch 961/2000
6/6 [==============================] - 0s 259us/sample - loss: 28.7902
Epoch 962/2000
6/6 [==============================] - 0s 278us/sample - loss: 28.7629
Epoch 963/2000
6/6 [==============================] - 0s 277us/sample - loss: 28.7357
Epoch 964/2000
6/6 [==============================] - 0s 277us/sample - loss: 28.7084
Epoch 965/2000
6/6 [==============================] - 0s 283us/sample - loss: 28.6811
Epoch 966/2000
6/6 [==============================] - 0s 278us/sample - loss: 28.6539
Epoch 967/2000
6/6 [==============================] - 0s 279us/sample - loss: 28.6266
Epoch 968/2000
6/6 [==============================] - 0s 288us/sample - loss: 28.5993
Epoch 969/2000
6/6 [==============================] - 0s 284us/sample - loss: 28.5720
Epoch 970/2000
6/6 [==============================] - 0s 298us/sample - loss: 28.5447
Epoch 971/2000
6/6 [==============================] - 

Epoch 1055/2000
6/6 [==============================] - 0s 328us/sample - loss: 26.1835
Epoch 1056/2000
6/6 [==============================] - 0s 490us/sample - loss: 26.1553
Epoch 1057/2000
6/6 [==============================] - 0s 401us/sample - loss: 26.1271
Epoch 1058/2000
6/6 [==============================] - 0s 346us/sample - loss: 26.0988
Epoch 1059/2000
6/6 [==============================] - 0s 373us/sample - loss: 26.0706
Epoch 1060/2000
6/6 [==============================] - 0s 474us/sample - loss: 26.0422
Epoch 1061/2000
6/6 [==============================] - 0s 397us/sample - loss: 26.0140
Epoch 1062/2000
6/6 [==============================] - 0s 379us/sample - loss: 25.9857
Epoch 1063/2000
6/6 [==============================] - 0s 482us/sample - loss: 25.9574
Epoch 1064/2000
6/6 [==============================] - 0s 379us/sample - loss: 25.9290
Epoch 1065/2000
6/6 [==============================] - 0s 398us/sample - loss: 25.9007
Epoch 1066/2000
6/6 [======================

6/6 [==============================] - 0s 429us/sample - loss: 23.4302
Epoch 1150/2000
6/6 [==============================] - 0s 332us/sample - loss: 23.3989
Epoch 1151/2000
6/6 [==============================] - 0s 381us/sample - loss: 23.3675
Epoch 1152/2000
6/6 [==============================] - 0s 456us/sample - loss: 23.3361
Epoch 1153/2000
6/6 [==============================] - 0s 385us/sample - loss: 23.3047
Epoch 1154/2000
6/6 [==============================] - 0s 345us/sample - loss: 23.2732
Epoch 1155/2000
6/6 [==============================] - 0s 489us/sample - loss: 23.2418
Epoch 1156/2000
6/6 [==============================] - 0s 432us/sample - loss: 23.2104
Epoch 1157/2000
6/6 [==============================] - 0s 396us/sample - loss: 23.1788
Epoch 1158/2000
6/6 [==============================] - 0s 309us/sample - loss: 23.1473
Epoch 1159/2000
6/6 [==============================] - 0s 422us/sample - loss: 23.1158
Epoch 1160/2000
6/6 [==============================] - 0s 4

Epoch 1244/2000
6/6 [==============================] - 0s 790us/sample - loss: 20.4515
Epoch 1245/2000
6/6 [==============================] - 0s 884us/sample - loss: 20.4203
Epoch 1246/2000
6/6 [==============================] - 0s 885us/sample - loss: 20.3911
Epoch 1247/2000
6/6 [==============================] - 0s 789us/sample - loss: 20.3603
Epoch 1248/2000
6/6 [==============================] - 0s 620us/sample - loss: 20.3281
Epoch 1249/2000
6/6 [==============================] - 0s 817us/sample - loss: 20.2977
Epoch 1250/2000
6/6 [==============================] - 0s 504us/sample - loss: 20.2671
Epoch 1251/2000
6/6 [==============================] - 0s 533us/sample - loss: 20.2361
Epoch 1252/2000
6/6 [==============================] - 0s 517us/sample - loss: 20.2057
Epoch 1253/2000
6/6 [==============================] - 0s 386us/sample - loss: 20.1744
Epoch 1254/2000
6/6 [==============================] - 0s 380us/sample - loss: 20.1436
Epoch 1255/2000
6/6 [======================

6/6 [==============================] - 0s 300us/sample - loss: 17.4919
Epoch 1339/2000
6/6 [==============================] - 0s 340us/sample - loss: 17.4599
Epoch 1340/2000
6/6 [==============================] - 0s 288us/sample - loss: 17.4277
Epoch 1341/2000
6/6 [==============================] - 0s 264us/sample - loss: 17.3951
Epoch 1342/2000
6/6 [==============================] - 0s 323us/sample - loss: 17.3622
Epoch 1343/2000
6/6 [==============================] - 0s 316us/sample - loss: 17.3290
Epoch 1344/2000
6/6 [==============================] - 0s 273us/sample - loss: 17.2954
Epoch 1345/2000
6/6 [==============================] - 0s 350us/sample - loss: 17.2620
Epoch 1346/2000
6/6 [==============================] - 0s 390us/sample - loss: 17.2291
Epoch 1347/2000
6/6 [==============================] - 0s 474us/sample - loss: 17.1965
Epoch 1348/2000
6/6 [==============================] - 0s 407us/sample - loss: 17.1640
Epoch 1349/2000
6/6 [==============================] - 0s 3

Epoch 1433/2000
6/6 [==============================] - 0s 378us/sample - loss: 14.3428
Epoch 1434/2000
6/6 [==============================] - 0s 317us/sample - loss: 14.3094
Epoch 1435/2000
6/6 [==============================] - 0s 358us/sample - loss: 14.2757
Epoch 1436/2000
6/6 [==============================] - 0s 376us/sample - loss: 14.2460
Epoch 1437/2000
6/6 [==============================] - 0s 374us/sample - loss: 14.2156
Epoch 1438/2000
6/6 [==============================] - 0s 433us/sample - loss: 14.1838
Epoch 1439/2000
6/6 [==============================] - 0s 410us/sample - loss: 14.1523
Epoch 1440/2000
6/6 [==============================] - 0s 555us/sample - loss: 14.1178
Epoch 1441/2000
6/6 [==============================] - 0s 323us/sample - loss: 14.0852
Epoch 1442/2000
6/6 [==============================] - 0s 338us/sample - loss: 14.0548
Epoch 1443/2000
6/6 [==============================] - 0s 323us/sample - loss: 14.0234
Epoch 1444/2000
6/6 [======================

6/6 [==============================] - 0s 463us/sample - loss: 11.3676
Epoch 1528/2000
6/6 [==============================] - 0s 526us/sample - loss: 11.3376
Epoch 1529/2000
6/6 [==============================] - 0s 371us/sample - loss: 11.3070
Epoch 1530/2000
6/6 [==============================] - 0s 595us/sample - loss: 11.2759
Epoch 1531/2000
6/6 [==============================] - 0s 634us/sample - loss: 11.2440
Epoch 1532/2000
6/6 [==============================] - 0s 572us/sample - loss: 11.2117
Epoch 1533/2000
6/6 [==============================] - 0s 547us/sample - loss: 11.1795
Epoch 1534/2000
6/6 [==============================] - 0s 574us/sample - loss: 11.1467
Epoch 1535/2000
6/6 [==============================] - 0s 526us/sample - loss: 11.1167
Epoch 1536/2000
6/6 [==============================] - 0s 395us/sample - loss: 11.0865
Epoch 1537/2000
6/6 [==============================] - 0s 565us/sample - loss: 11.0535
Epoch 1538/2000
6/6 [==============================] - 0s 5

Epoch 1622/2000
6/6 [==============================] - 0s 330us/sample - loss: 8.5195
Epoch 1623/2000
6/6 [==============================] - 0s 299us/sample - loss: 8.4884
Epoch 1624/2000
6/6 [==============================] - 0s 308us/sample - loss: 8.4598
Epoch 1625/2000
6/6 [==============================] - 0s 308us/sample - loss: 8.4326
Epoch 1626/2000
6/6 [==============================] - 0s 313us/sample - loss: 8.4041
Epoch 1627/2000
6/6 [==============================] - 0s 357us/sample - loss: 8.3755
Epoch 1628/2000
6/6 [==============================] - 0s 286us/sample - loss: 8.3470
Epoch 1629/2000
6/6 [==============================] - 0s 300us/sample - loss: 8.3181
Epoch 1630/2000
6/6 [==============================] - 0s 333us/sample - loss: 8.2887
Epoch 1631/2000
6/6 [==============================] - 0s 321us/sample - loss: 8.2613
Epoch 1632/2000
6/6 [==============================] - 0s 336us/sample - loss: 8.2331
Epoch 1633/2000
6/6 [==============================] -

Epoch 1718/2000
6/6 [==============================] - 0s 330us/sample - loss: 5.9417
Epoch 1719/2000
6/6 [==============================] - 0s 293us/sample - loss: 5.9163
Epoch 1720/2000
6/6 [==============================] - 0s 315us/sample - loss: 5.8908
Epoch 1721/2000
6/6 [==============================] - 0s 327us/sample - loss: 5.8665
Epoch 1722/2000
6/6 [==============================] - 0s 301us/sample - loss: 5.8415
Epoch 1723/2000
6/6 [==============================] - 0s 307us/sample - loss: 5.8178
Epoch 1724/2000
6/6 [==============================] - 0s 352us/sample - loss: 5.7932
Epoch 1725/2000
6/6 [==============================] - 0s 302us/sample - loss: 5.7679
Epoch 1726/2000
6/6 [==============================] - 0s 376us/sample - loss: 5.7444
Epoch 1727/2000
6/6 [==============================] - 0s 326us/sample - loss: 5.7195
Epoch 1728/2000
6/6 [==============================] - 0s 303us/sample - loss: 5.6957
Epoch 1729/2000
6/6 [==============================] -

Epoch 1814/2000
6/6 [==============================] - 0s 284us/sample - loss: 3.8090
Epoch 1815/2000
6/6 [==============================] - 0s 381us/sample - loss: 3.7907
Epoch 1816/2000
6/6 [==============================] - 0s 327us/sample - loss: 3.7710
Epoch 1817/2000
6/6 [==============================] - 0s 311us/sample - loss: 3.7513
Epoch 1818/2000
6/6 [==============================] - 0s 346us/sample - loss: 3.7316
Epoch 1819/2000
6/6 [==============================] - 0s 369us/sample - loss: 3.7141
Epoch 1820/2000
6/6 [==============================] - 0s 362us/sample - loss: 3.6952
Epoch 1821/2000
6/6 [==============================] - 0s 385us/sample - loss: 3.6742
Epoch 1822/2000
6/6 [==============================] - 0s 361us/sample - loss: 3.6549
Epoch 1823/2000
6/6 [==============================] - 0s 393us/sample - loss: 3.6364
Epoch 1824/2000
6/6 [==============================] - 0s 383us/sample - loss: 3.6175
Epoch 1825/2000
6/6 [==============================] -

Epoch 1910/2000
6/6 [==============================] - 0s 290us/sample - loss: 2.2176
Epoch 1911/2000
6/6 [==============================] - 0s 276us/sample - loss: 2.2041
Epoch 1912/2000
6/6 [==============================] - 0s 294us/sample - loss: 2.1900
Epoch 1913/2000
6/6 [==============================] - 0s 313us/sample - loss: 2.1755
Epoch 1914/2000
6/6 [==============================] - 0s 279us/sample - loss: 2.1617
Epoch 1915/2000
6/6 [==============================] - 0s 278us/sample - loss: 2.1489
Epoch 1916/2000
6/6 [==============================] - 0s 321us/sample - loss: 2.1355
Epoch 1917/2000
6/6 [==============================] - 0s 300us/sample - loss: 2.1214
Epoch 1918/2000
6/6 [==============================] - 0s 273us/sample - loss: 2.1083
Epoch 1919/2000
6/6 [==============================] - 0s 294us/sample - loss: 2.0951
Epoch 1920/2000
6/6 [==============================] - 0s 326us/sample - loss: 2.0816
Epoch 1921/2000
6/6 [==============================] -

In [14]:
# demonstrate prediction
x_input = array([[70, 75], [80, 85], [90, 95]])
x_input = x_input.reshape((1, n_steps_in, n_features))
print(x_input)
print(x_input.shape)
yhat = models.predict(tf.cast(x_input, tf.float32), verbose=True)
print(yhat)
print(yhat.shape)

[[[70 75]
  [80 85]
  [90 95]]]
(1, 3, 2)
1/1 [==============================] - 0s 37ms/sample
[[185.75688 208.19626]]
(1, 2)
